# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evedb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvGroups',
            new_name='InvGroup',
        ),
    ]
