# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evedb', '0002_auto_20170515_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('token_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
