# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evedb', '0003_sstokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSTokens',
            new_name='SSToken',
        ),
    ]
